# Generated by Django 4.1.10 on 2023-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_profile_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.FileField(blank=True, null=True, upload_to='chapters/'),
        ),
    ]
