# Generated by Django 4.1.10 on 2023-10-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_chapter_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
